development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_production
  username: root
  password: root
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: peatio_test

production:
  <<: *defaults
  database: peatio_production
